# Default values for raft-cluster
replicaCount: 3

image:
  repository: raft-consensus
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  grpcPort: 50051
  metricsPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: raft-cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Raft-specific configuration
raft:
  electionTimeoutMin: 150
  electionTimeoutMax: 300
  heartbeatInterval: 50
  maxAppendEntries: 100
  enableMetrics: true

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    scrapeTimeout: 10s

# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress: []
